# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ridge_request.proto\x12\x13hrt_interfaces.core\"i\n\x11OpenBridgeRequest\x12\x16\n\x0eoutbound_topic\x18\x01 \x01(\t\x12<\n\x0cmessage_type\x18\x02 \x01(\x0e\x32&.hrt_interfaces.core.BridgeMessageType\"\'\n\x12\x43loseBridgeRequest\x12\x11\n\tbridge_id\x18\x01 \x01(\t*=\n\x11\x42ridgeMessageType\x12\x16\n\x12\x42RIDGE_MSG_UNKNOWN\x10\x00\x12\x07\n\x03IMU\x10\x01\x12\x07\n\x03\x44WM\x10\x02\x62\x06proto3')

_BRIDGEMESSAGETYPE = DESCRIPTOR.enum_types_by_name['BridgeMessageType']
BridgeMessageType = enum_type_wrapper.EnumTypeWrapper(_BRIDGEMESSAGETYPE)
BRIDGE_MSG_UNKNOWN = 0
IMU = 1
DWM = 2


_OPENBRIDGEREQUEST = DESCRIPTOR.message_types_by_name['OpenBridgeRequest']
_CLOSEBRIDGEREQUEST = DESCRIPTOR.message_types_by_name['CloseBridgeRequest']
OpenBridgeRequest = _reflection.GeneratedProtocolMessageType('OpenBridgeRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENBRIDGEREQUEST,
  '__module__' : 'bridge_request_pb2'
  # @@protoc_insertion_point(class_scope:hrt_interfaces.core.OpenBridgeRequest)
  })
_sym_db.RegisterMessage(OpenBridgeRequest)

CloseBridgeRequest = _reflection.GeneratedProtocolMessageType('CloseBridgeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEBRIDGEREQUEST,
  '__module__' : 'bridge_request_pb2'
  # @@protoc_insertion_point(class_scope:hrt_interfaces.core.CloseBridgeRequest)
  })
_sym_db.RegisterMessage(CloseBridgeRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BRIDGEMESSAGETYPE._serialized_start=193
  _BRIDGEMESSAGETYPE._serialized_end=254
  _OPENBRIDGEREQUEST._serialized_start=45
  _OPENBRIDGEREQUEST._serialized_end=150
  _CLOSEBRIDGEREQUEST._serialized_start=152
  _CLOSEBRIDGEREQUEST._serialized_end=191
# @@protoc_insertion_point(module_scope)